services:
  realsense:
    image: ctumrs/bluefox2:unstable
    #build: .
    privileged: true
    network_mode: "host"
    configs:
      - source: cfg_yaml
        target: /custom_config.yaml
        mode: 0444  # read-only permissions
    command: custom_config:=/custom_config.yaml
    environment:
      - UAV_NAME=uav1

configs:
  cfg_yaml:
    content: |
      /uav1/mv_26808027/bluefox2_single:
        ros__parameters:
          fps: 25
          remappings:
            '/uav1/mv_26808027/image_raw': /abc